@startuml

actor Client


Client -> Blockchain : Make allocation request (erasure code, size, expiry)
Blockchain -> Blockchain : Assigns the blobbers \ncreates the read/write pools for allocation
Blockchain --> Client : Allocation status, if success, list of blobbers selected


loop till done
    Client -> Blobber : Upload the file (path, metadata, connection id)
    Blobber --> Client : Upload successful
end
Client -> Blobber : commit the connection and pass the writemarker (allocation root, prev allocation root, upload size) 
Blobber --> Client : commit success / failure


Blobber -> Blockchain : redeem the write marker in the order received
note right
async redeemption
not blocking uploads
end note

Blockchain -> Blockchain : Move tokens from write pool to challenge pool

@enduml