version: "3"
services:

  blobber:
    build:
      context: ${DOCKER_CODEBASE}
      dockerfile: ./docker.aws/build.blobber/Dockerfile

    image: ${IMAGE_NAME}:${IMAGE_TAG}

    environment:
    - DOCKER= true

    user: ${ZCHAIN_USER}:${ZCHAIN_GROUP}

    command: /0chain/bin/blobber --deployment_mode 0 --keys_file /0chain/config/blobber.txt --nodes_file nodes --files_dir /0chain/files --badger_dir /0chain/data

    ports:
    - "5051:5051"

    volumes:
    - /0chain/config:/0chain/config
    - /0chain/data:/0chain/data
    - /0chain/data/files:/0chain/files
    - /0chain/files:/0chain/files
    - /0chain/logs:/0chain/logs

    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: 10M

    networks:
      default:

networks:
  default:
    driver: bridge

