basePath: /
definitions:
    UploadResult:
        properties:
            content_hash:
                type: string
                x-go-name: Hash
            filename:
                type: string
                x-go-name: Filename
            merkle_root:
                type: string
                x-go-name: MerkleRoot
            size:
                format: int64
                type: integer
                x-go-name: Size
            upload_length:
                description: UploadLength indicates the size of the entire upload in bytes. The value MUST be a non-negative integer.
                format: int64
                type: integer
                x-go-name: UploadLength
            upload_offset:
                description: Upload-Offset indicates a byte offset within a resource. The value MUST be a non-negative integer.
                format: int64
                type: integer
                x-go-name: UploadOffset
        type: object
        x-go-package: github.com/0chain/blobber/code/go/0chain.net/blobbercore/blobberhttp
host: localhost:7171
info:
    title: '0chain Api:'
    version: 0.0.1
paths:
    /v1/block/magic/get:
        get:
            description: a handler to respond to block queries
            operationId: getmagicblock
            responses:
                "200":
                    description: ""
                "404":
                    description: ""
    /v1/file/rename/{allocation}:
        get:
            description: rename an allocation
            operationId: renameallocation
            parameters:
                - description: offset
                  in: path
                  name: allocation
                  required: true
                  type: string
            responses:
                "200":
                    description: UploadResult
                    schema:
                        $ref: '#/definitions/UploadResult'
                "400":
                    description: ""
                "500":
                    description: ""
produces:
    - application/json
schemes:
    - http
    - https
securityDefinitions:
    apiKey:
        in: header
        name: authorization
        type: apiKey
swagger: "2.0"
