version: 1.0

logging:
  level: "info"
  console: false # printing log to console is only supported in development mode

server_chain:
  id: "0afc093ffb509f059c55478bc1a60351cef7b4e9c008a53a6cc8241ca8617dfe"
  owner: "65dfe7e15ca2f689edda6eff3d5c36e8c0975792fa443c5f5413fbca27c49567"
  genesis_block:
    id: "ed79cae70d439c11258236da1dfa6fc550f7cc569768304623e8fbd7d70efae4"
contentref_cleaner:
  frequency: 30
  tolerance: 3600
openconnection_cleaner:
  frequency: 30
  tolerance: 3600
writemarker_redeem:
  frequency: 10
  num_workers : 5
readmarker_redeem:
  frequency: 10
  num_workers : 5
challenge_response:
  frequency: 30
  num_workers: 5
