basePath: /
host: localhost:7171
info:
    title: '0chain Api:'
    version: 0.0.1
paths:
    /v1/block/magic/get:
        get:
            description: a handler to respond to block queries
            operationId: getmagicblock
            responses:
                "200":
                    description: ""
                "404":
                    description: ""
produces:
    - application/json
schemes:
    - http
    - https
securityDefinitions:
    apiKey:
        in: header
        name: authorization
        type: apiKey
swagger: "2.0"
