version: "3"
services:
  postgres:
    image: postgres:14
    volumes:
      - ./blobber${BLOBBER}/data/postgresql:/var/lib/postgresql/data
      - ./sql_init:/docker-entrypoint-initdb.d
    networks:
      default:
    ports:
      - "543${BLOBBER}:5432"
    labels:
      zchain: "postgres"
    shm_size: 4gb   
  validator:
    image: validator
    environment:
      - DOCKER= true
    volumes:
      - ../config:/validator/config
      - ./blobber${BLOBBER}/data:/validator/data
      - ./blobber${BLOBBER}/log:/validator/log
      - ./keys_config:/validator/keysconfig
    ports:
      - "506${BLOBBER}:506${BLOBBER}"
    labels:
      zchain: "validator"
    command: ./bin/validator --port 506${BLOBBER} --hostname localhost --deployment_mode 0 --keys_file keysconfig/bnode${BLOBBER}_keys.txt --log_dir /validator/log
    networks:
      default:
      testnet0:
        ipv4_address: 198.18.0.6${BLOBBER}

  blobber:
    image: blobber
    stop_grace_period: 1m30s
    depends_on:
      - validator
    links:
      - validator:validator
    volumes:
      - ../config:/blobber/config
      - ./blobber${BLOBBER}/files:/blobber/files
      - ./blobber${BLOBBER}/data:/blobber/data
      - ./blobber${BLOBBER}/log:/blobber/log
      - ./keys_config:/blobber/keysconfig
    ports:
      - "505${BLOBBER}:505${BLOBBER}"
      - "703${BLOBBER}:703${BLOBBER}"
    labels:
      zchain: "blobber"
    command: ./bin/blobber --port 505${BLOBBER} --grpc_port 703${BLOBBER} --hostname localhost --deployment_mode 0 --keys_file keysconfig/bnode${BLOBBER}_keys.txt --files_dir /blobber/files --log_dir /blobber/log --db_dir /blobber/data
    networks:
      default:
      testnet0:
        ipv4_address: 198.18.0.9${BLOBBER}

networks:
  default:
    driver: bridge
  testnet0:
    external: true
    # driver: bridge
    # ipam:
    #   config:
    #     - subnet: 198.18.0.0/15
    #     - gateway: 198.18.0.255

volumes:
  data:
  config:
  bin:
