version: '3'
services:
  postgres:
    image: postgres:11
    volumes:
      - ./blobber${BLOBBER}/data/postgresql:/var/lib/postgresql/data
    networks:
      default:
    ports:
      - "543${BLOBBER}:5432"
  postgres-post:
    image: postgres:11
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
    volumes:
      - ../bin:/blobber/bin
      - ../sql:/blobber/sql
    command: bash /blobber/bin/postgres-entrypoint.sh
    links:
      - postgres:postgres
  
  blobber:
    environment:
      - DOCKER= true
    depends_on:
      - postgres-post
    links:
      - postgres-post:postgres-post
    build: 
      context: ../
      dockerfile: ./docker.local/Dockerfile
    volumes:
     - ./keys_config:/blobber/keysconfig
     - ../config:/blobber/config
     - ./blobber${BLOBBER}/files:/blobber/files
     - ./blobber${BLOBBER}/data:/blobber/data
     - ./blobber${BLOBBER}/log:/blobber/log
    ports:
      - "505${BLOBBER}:505${BLOBBER}"
    networks:
      default:
      testnet0:
        ipv4_address: 198.18.0.9${BLOBBER}
    command: ./bin/blobber --deployment_mode 0 --keys_file keysconfig/bnode${BLOBBER}_keys.txt --nodes_file single_machine_3_nodes --files_dir /blobber/files --log_dir /blobber/log --db_dir /blobber/data


networks:
  default:
    driver: bridge
  testnet0:
    external: true
volumes:
  data:
  config:
  bin: