version: '2.2'
services:

  blobber:
    environment:
      - DOCKER= true
    build: 
      context: ../
      dockerfile: ./docker.local/Dockerfile
    volumes:
     - ./config:/blobber/config
     - ./blobber${BLOBBER}/files:/blobber/files
    ports:
     - "505${BLOBBER}:505${BLOBBER}"
    #command: ./blobber --deployment_mode 0 --deployment_mode 0 --keys_file config/bnode${BLOBBER}_keys.txt --nodes_file config/single_machine_3_nodes.txt
    command: ./blobber --deployment_mode 0 --deployment_mode 0 --keys_file config/bnode${BLOBBER}_keys.txt --nodes_file single_machine_3_nodes
