version: "3"
services:
  postgres:
    container_name: blobber-postgres-${BLOBBER}
    image: postgres:14
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ../config/postgresql.conf:/etc/postgresql/postgresql.conf
      - ${PROJECT_ROOT_SSD}/blobber${BLOBBER}/data/postgresql:/var/lib/postgresql/data
      - ./sql_init:/docker-entrypoint-initdb.d
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    # ports:
    #   - 5432:5432
    networks:
      testnet0:
        ipv4_address: 198.18.8.${BLOBBER}
    restart: on-failure:5

  validator:
    container_name: validator-${BLOBBER}
    image: 0chaindev/validator:staging
    environment:
      - DOCKER=true
    depends_on:
      - postgres
    volumes:
      - ../config:/validator/config
      - ${PROJECT_ROOT_HDD}/validator${BLOBBER}/data:/validator/data
      - ${PROJECT_ROOT_HDD}/validator${BLOBBER}/log:/validator/log
      - ./keys_config:/validator/keysconfig
    ports:
      - "506${BLOBBER}:506${BLOBBER}"
    command: ./bin/validator --port 506${BLOBBER} --hostname localhost --deployment_mode 0 --keys_file keysconfig/b0vnode${BLOBBER}_keys.txt --log_dir /validator/log  --hosturl https://helm.0chain.net/validator0${BLOBBER}
    networks:
      testnet0:
        ipv4_address: 198.18.7.${BLOBBER}
    restart: on-failure:5

  blobber:
    container_name: blobber-${BLOBBER}
    image: 0chaindev/blobber:staging
    environment:
      - DOCKER=true
    depends_on:
      - validator
    volumes:
      - ../config:/blobber/config
      - ${PROJECT_ROOT_HDD}/blobber${BLOBBER}/files:/blobber/files
      - ${PROJECT_ROOT_HDD}/blobber${BLOBBER}/data:/blobber/data
      - ${PROJECT_ROOT_HDD}/blobber${BLOBBER}/log:/blobber/log
      - ./keys_config:/blobber/keysconfig
      - ${PROJECT_ROOT_HDD}/blobber${BLOBBER}/data/tmp:/tmp
    ports:
      - "505${BLOBBER}:505${BLOBBER}"
      - "703${BLOBBER}:703${BLOBBER}"
    command: ./bin/blobber --port 505${BLOBBER} --grpc_port 703${BLOBBER} --hostname localhost --deployment_mode 0 --keys_file keysconfig/b0bnode${BLOBBER}_keys.txt --files_dir /blobber/files --log_dir /blobber/log --db_dir /blobber/data --hosturl https://helm.0chain.net/blobber0${BLOBBER}
    networks:
      testnet0:
        ipv4_address: 198.18.6.${BLOBBER}
    restart: on-failure:5

networks:
  testnet0:
    external: true

volumes:
  data:
  config:
  bin:
