@startuml
collections Javascript
control 0ChainSDK
Javascript->0ChainSDK: WebAssembly.Instantiate(...)
Javascript->0ChainSDK: ZCNWebSdkSetupEncoder(numdatashards, numparityshards)
group Encode/Split
    Javascript->0ChainSDK: ZCNWebSdkEncode(Uint8ArrayBuffer, CallbackFunction)
    loop numdatashards+parityshards
        0ChainSDK->Javascript: CallbackFunction(shardnum, shardlength, pointer)
    end
end
group Decode/Reconstruct
    Javascript->0ChainSDK: ZCNWebSdkDecode([]Uint8ArrayBuffer, CallbackFunction)
    0ChainSDK->Javascript: CallbackFunction(totallength, pointer)
end
@enduml
