name: Benchmark tests

on:
  push:
    branches: [ master, staging ]

jobs:
  benchmark:
    runs-on: [self-hosted, load-test]
    steps:
      - name: Setup go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: '1.16' # The Go version to download (if necessary) and use.

      - name: Clone blobber
        uses: actions/checkout@v2

      - name: Set GITHUB_ENV
        run: |
            echo "BRANCH=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
            echo "GOSDK=$(echo $(dirname $(pwd)))/gosdk" >> $GITHUB_ENV
            echo "TAG=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g' )" >> $GITHUB_ENV

      - name: Run benchmark
        run: CGO_ENABLED=1 go test -tags bn256 -benchmem -run="BenchmarkUploadFile*" -bench="BenchmarkUploadFile*"   ./... | tee benchmark.txt