name: Benchmark tests

concurrency:
  group: "benchmark-${{ github.ref }}"
  cancel-in-progress: true

on:
  push:
    branches: [ master, staging ]

jobs:
  benchmark:
    runs-on: [self-hosted, conductor-test]
    steps:
      - name: Setup go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: '1.17' # The Go version to download (if necessary) and use.

      - name: Clone blobber
        uses: actions/checkout@v2

      - name: Run benchmark
        run: CGO_ENABLED=1 go test -tags bn256 -benchmem -run="BenchmarkUploadFile*" -bench="BenchmarkUploadFile*"   ./... | tee benchmark.txt