name: CI

on:
  push:

  release:
    types:
      - published
  pull_request:
    paths-ignore:
      - '**.md'

env:
  BLOBBER_REGISTRY: ${{ secrets.BLOBBER_REGISTRY }}
  VALIDATOR_REGISTRY: ${{ secrets.VALIDATOR_REGISTRY }}

jobs:
  integration_test:
    runs-on: [self-hosted,build]
    timeout-minutes: 40
    steps:
  
      - name: Setup go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: '1.16' # The Go version to download (if necessary) and use.

      - name: Clone Blobber
        uses: actions/checkout@v1

      - name: Build test environment and run tests
        run: |
          sed -i '/#expose_ci_port/c\    ports:\n      - "5432:5432"' ./docker.local/b0docker-compose.yml
          ./docker.local/bin/blobber.init.setup.sh
          docker network ls | grep testnet0 || docker network create --driver=bridge --subnet=198.18.0.0/15 --gateway=198.18.0.255 testnet0
          ./docker.local/bin/build.base.sh
          ./docker.local/bin/build.blobber.sh
          ./docker.local/bin/build.validator.sh
          cd docker.local/blobber1
          ../bin/blobber.start_bls.sh </dev/null &>/dev/null &
          cd ../..
      
          go16=$(which go)
          sudo $go16 test -tags bn256  ./... -args integration;
  golangci:
    name: lint
    runs-on: [self-hosted, tests-suite]
    steps:
      - name: Setup go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: '1.16' # The Go version to download (if necessary) and use.
      - uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          args: --timeout=2m0s

  buf-build:
    runs-on: [self-hosted, tests-suite]
    steps:
      - name: Check out code
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: setup golang
        if: success()
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: run buf commands
        if: success()
        run: make local

  dockerize_blobber:
    runs-on: [self-hosted, build]
    needs: integration_test
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
    - uses: actions/checkout@v2

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build
      run: |
        docker build -t $BLOBBER_REGISTRY:$TAG -f docker.local/Dockerfile .
        docker push $BLOBBER_REGISTRY:$TAG
      env:
        TAG: ${{ steps.get_version.outputs.VERSION }}

  dockerize_validator:
    runs-on: [self-hosted, build]
    needs: integration_test
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
    - uses: actions/checkout@v2

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build
      run: |
        docker build -t $VALIDATOR_REGISTRY:$TAG -f docker.local/ValidatorDockerfile .
        docker push $VALIDATOR_REGISTRY:$TAG
      env:
        TAG: ${{ steps.get_version.outputs.VERSION }}