name: CI

on:
  push:
  release:
    types:
      - published

env:
  BLOBBER_REGISTRY: ${{ secrets.BLOBBER_REGISTRY }}
  VALIDATOR_REGISTRY: ${{ secrets.VALIDATOR_REGISTRY }}

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x
      - uses: actions/checkout@v2
      # In this step, this action saves a list of existing images,
      # the cache is created without them in the post run.
      # It also restores the cache if it exists.
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      - name: Build
        run: |
          docker network create --driver=bridge --subnet=198.18.0.0/15 --gateway=198.18.0.255 testnet0
          ./docker.local/bin/build.blobber.sh

  test:
    runs-on: ubuntu-20.04
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.x
    - uses: actions/checkout@v2
    - name: Test
      run: make test

  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x
      - uses: actions/checkout@v2
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.38.0
          golangci-lint --version
      - name: Lint
        run: make lint


  generated-files-integrity:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          cd code/go/0chain.net/blobbercore
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway \
          github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2 \
          google.golang.org/protobuf/cmd/protoc-gen-go \
          google.golang.org/grpc/cmd/protoc-gen-go-grpc
          git reset --hard
      - name: Generate Files
        run: |
          cd code/go/0chain.net/blobbercore
          ./scripts/generate-grpc.sh
      - name: Fail if any file has changed
        run: if output=$(git status --porcelain) && [ -z "$output" ]; then exit 0; else git status; exit 1; fi;

  dockerize_blobber:
    runs-on: ubuntu-20.04
    needs: test
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
    - uses: actions/checkout@v2

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build
      run: |
        docker build -t $BLOBBER_REGISTRY:$TAG -f docker.local/Dockerfile .
        docker push $BLOBBER_REGISTRY:$TAG
      env:
        TAG: ${{ steps.get_version.outputs.VERSION }}

  dockerize_validator:
    runs-on: ubuntu-20.04
    needs: test
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
    - uses: actions/checkout@v2

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build
      run: |
        docker build -t $VALIDATOR_REGISTRY:$TAG -f docker.local/ValidatorDockerfile .
        docker push $VALIDATOR_REGISTRY:$TAG
      env:
        TAG: ${{ steps.get_version.outputs.VERSION }} 
 
  api_tests:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          repository: 0chain/0chainAPI
          token: ${{ secrets.SVC_ACCOUNT_SECRET }}
      - name: Install Node
        uses: actions/setup-node@v1
        with: 
          node-version: '12.x'

      - name: Install newman
        run: |
         npm install -g newman
         npm install -g newman-reporter-htmlextra
         
      - name: Set env BRANCH
        run: echo "BRANCH=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')" >> $GITHUB_ENV

      - name: Make Directory for results
        run: mkdir -p ./${BRANCH}/latest
         

      - name: Run POSTMAN collection
        run: |
           exit_code=0
           newman run "./Postman Collections/0chain-regressions.json" -e "./Postman Collections/Environments/${{ secrets.TEMP_API_TESTNET_TARGET }}.postman_environment.json" -r cli,htmlextra --reporter-htmlextra-export "./${BRANCH}/latest/index.html" --reporter-htmlextra-darkTheme --reporter-htmlextra-showEnvironmentData --reporter-htmlextra-showGlobalData --reporter-htmlextra-browserTitle "${GITHUB_SHA}" --reporter-htmlextra-title "0Chain API Regression Tests" --reporter-htmlextra-template "./Postman Collections/Data/0chain-dashboard-template.hbs"  --color on || exit_code=$? 
           cp -R ./${BRANCH}/latest ./${BRANCH}/${GITHUB_SHA}
           exit $exit_code
    
      - name: Output the run Details
        if: always()
        uses: actions/upload-artifact@v2
        with: 
         name: RunReports
         path: "./${{ env.BRANCH }}/latest"
         
      - name: Deploy report page
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: test_reports
          keep_files: true
          github_token: ${{ secrets.SVC_ACCOUNT_SECRET }}
          publish_dir: "./${{ env.BRANCH }}"
          destination_dir: "./${{ env.BRANCH }}"
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'    
          
      - name: Report Link
        if: always()
        run: echo "https://0chain.github.io/blobber/${{ env.BRANCH }}/${GITHUB_SHA}" 
