name: CICD_Hetzner_Test

on:
  workflow_dispatch:
    inputs:
      latest_tag:
        description: 'Type yes for building latest tag'
        default: 'no'
        required: true
      kube_ns:
        description: 'Type namespace'
        required: true
        
env:
  KUBE_NAMESPACE: ${{ github.event.inputs.kube_ns }}

jobs:
  dockerize_blobber:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Get the Version for Tagging
      id: get_version
      run: |
        BRANCH=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')
        SHORT_SHA=$(echo $GITHUB_SHA | head -c 8)
        echo ::set-output name=BRANCH::${BRANCH}
        echo ::set-output name=VERSION::${BRANCH}-${SHORT_SHA}
    
    - name: Get Kube Config File
      id: get_kube_config
      run: |
        KUBE_CONFIG1=$(echo KUBE_CONFIG_DATA)
        echo ::set-output name=KUBE_CONFIG2::${KUBE_CONFIG1}_${KUBE_NAMESPACE} 

    - name: Check File Name
      run: |
        echo $KUBE_NAMESPACE
        echo ${{ steps.get_kube_config.outputs.KUBE_CONFIG1 }}
        echo ${{ steps.get_kube_config.outputs.KUBE_CONFIG2 }}

    - name: Update Blobber Image to Kubernetes Cluster
      uses: actions-hub/kubectl@master
      with:
        args: get pods -A
      env:
        TAG: ${{ steps.get_version.outputs.VERSION }}
        KUBE_CONFIG: ${{ secrets[steps.get_kube_config.outputs.KUBE_CONFIG2] }}
