name: CICD-01

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'image tag'
        required: true
        default: latest

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - uses: azure/setup-helm@v1
        with:
          version: 'v3.2.2'
      - name: Setup helm repo
        run: |
          helm repo add blobber http://0chain-helm-chart.s3-website.us-east-2.amazonaws.com/helmCharts/blobber
          helm repo upgrade
      - name: Setup kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.CICD01KC }}" | base64 -d > ~/.kube/config
      - name: Setup chain
        run: |
          helm upgrade --install blobber -n helmtest --set blobber.blobberImage.tag=${{ github.event.inputs.image }} --set validator.validatorImage.tag=${{ github.event.inputs.image }} zchain/helm