name: Tests

on:
  push: 
    branches:
      - master
      - staging
  pull_request:

jobs:
  unit_tests:
    runs-on: [self-hosted, load-test]
    steps:
      - name: Setup go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: '1.16' # The Go version to download (if necessary) and use.

      - name: Clone blobber
        uses: actions/checkout@v2

      # - name: Set GITHUB_ENV
      #   run: |
      #     echo "BRANCH=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
      #     echo "GOSDK=$(echo $(dirname $(pwd)))/gosdk" >> $GITHUB_ENV
      #     echo "TAG=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g' )" >> $GITHUB_ENV
         
      # - name: Clone gosdk
      #   run: |
      #     [ -d $GOSDK ] && rm -rf $GOSDK
      #     git clone https://github.com/0chain/gosdk.git $GOSDK
      #     cd $GOSDK
      #     git checkout $BRANCH
  
      - name: Run tests
        run: |
          cd $GITHUB_WORKSPACE/code/go/0chain.net/ 
          CGO_ENABLED=1 go test -tags bn256 -race -coverprofile=coverage.txt -covermode=atomic ./...
      # - name: Codecov
      #   run: |
      #     cd $GITHUB_WORKSPACE/code/go/0chain.net/
      #     bash <(curl -s https://codecov.io/bash)