name: Tests

concurrency:
  group: "tests-${{ github.ref }}"
  cancel-in-progress: true

on:
  push: 
    branches:
      - master
      - staging
    tags:
  pull_request:

jobs:
  linter:
    name: Lints
    runs-on: [self-hosted,docker-builds]
    steps:
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19 # The Go version to download (if necessary) and use.

      - name: Clone blobber
        uses: actions/checkout@v2

      - name: Buf-lint
        if: success()
        run: make local

      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=2m0s
          skip-cache: true
          skip-pkg-cache: true
          skip-build-cache: true


  unit-tests:
    name: Unit Tests
    runs-on: [self-hosted,docker-builds]
    steps:
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19 # The Go version to download (if necessary) and use.

      - name: Clone blobber
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          cd $GITHUB_WORKSPACE/code/go/0chain.net/ 
          CGO_ENABLED=1 go test -tags bn256 -race -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          # fail_ci_if_error: true
          files: ./code/go/0chain.net/coverage.txt
          flags: Unit-Tests
          verbose: true
