name: Tests

concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: true
  
on:
  push: 
    branches:
      - master
      - staging
    tags:
      - "*"
  pull_request:

jobs:
  unit_tests:
    name: "Unit Tests"
    runs-on: [self-hosted, build]
    steps:
      - name: Setup go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: '1.17' # The Go version to download (if necessary) and use.

      - name: Clone blobber
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          cd $GITHUB_WORKSPACE/code/go/0chain.net/ 
          CGO_ENABLED=1 go test -tags bn256 -race -coverprofile=coverage.txt -covermode=atomic ./...

  integration_test:
    name: "Integration Tests"
    needs: unit_tests
    runs-on: [ubuntu-20.04]
    timeout-minutes: 40
    steps:
  
      - name: Setup go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: '1.17' # The Go version to download (if necessary) and use.

      - name: Clone Blobber
        uses: actions/checkout@v1

      - name: Install Postgres
        run: |
          ./docker.local/bin/blobber.init.setup.sh
          cd docker.local/blobber1
          ../bin/blobber.start_github.sh
          docker ps
      - name: Run Tests
        run: |
          make local-build
          sudo make local-run &
          sleep 15
          running=0
          echo "checking blobber server status"
          if [ $running -eq 0 ]; then
            echo "checking blobber server status"
            curl 127.0.0.1:5051 && $running=1 || sleep 2
          fi

          echo =========================[ run tests ]=========================
          #sudo make integration-tests 
          go17=$(which go)
          root=$(pwd)
          sudo CGO_ENABLED=1 root=$root integration=1 $go17 test -tags bn256  ./...

  golangci:
    name: lint
    runs-on: [self-hosted, build]
    steps:
      - name: Setup go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: '1.17' # The Go version to download (if necessary) and use.
      - uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          args: --timeout=2m0s

  buf-build:
    runs-on: [self-hosted, build]
    steps:
      - name: Check out code
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: setup golang
        if: success()
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: run buf commands
        if: success()
        run: make local