name: Unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build blobber
        run: ./docker.local/bin/build.blobber.sh

      - name: run unit tests
        run: ./docker.local/bin/unit_test_check.sh